packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  cpu-features: false
  esbuild: true
  prisma: true
  vue-demi: true

overrides:
  onetime: 5.1.2
